### ISSUE TITLE
Le CSS est écrit

### ISSUE THREAD

**Issue by piline** [Kozea/www-media#11]

**Comment by hugobernard** [comment]
Suggestions ou interrogations de @piline

Il y a juste 3 points :
- Sur la page d'accueil il y a actuellement 3 phrases et 3 boutons "en savoir plus". Je pense que vous pourrez en laisser un seul qui ramène sur la page "à propos" (à voir, le plus simple pour vous une fois que le slider est intégré)

- Le menu : Actuellement il est fait entièrement en css au hover, mais je trouve que ca reste un peu bizarre d'avoir écris "menu" et que ça ne soit pas cliquable. Donc selon ce que vous en pensez vous pouvez faire le menu en javascript ( vous avez l'accord de Guillaume pour ça :))

- Pages métiers ( "je suis pharmacien", "je suis un labo", "je suis un groupement" ) : le premier article, le texte à gauche est centré par rapport à la hauteur du bloc de droite. Si vous trouvez ça bizarre vous pouvez changer

**Comment by liZe** [comment]
@hugobernard @annabellou @oliviakozea

- Sur la page d'accueil, je suis d'accord, le slider est peut-être de trop. Un seul lien qui amène sur la page « à propos » serait suffisant à mon avis. Sinon, je veux bien savoir vers quelles pages mènent les liens.
- Je trouve le menu vraiment chouette comme il est.
- L'alignement ne me choque pas.

**Comment by oliviakozea** [comment]
ok pr moi

**Comment by hugobernard** [comment]
### Général
- [ ] Les menus ont une même hauteur
- [ ] Les menus sont fixes
### Page À propos
- [ ] Le bloc "Alors pourquoi pas vous ?" à les bons padding sur Firefox
### Page Nos garanties
- [ ] Le titre de la page à les bonnes marges et l'indication "[Nos garanties]" est rajoutée
- [ ] La taille des texte corresond aux maquettes
- [ ] Le hover des textes fait apparaître (comme les titres) les illustrations
### Page Nos services
- [ ] Le titre de la page à les bonnes marges et l'indication "[Nos services]" est rajoutée
- [ ] Les prestations sont centrées dans les carrés
### Page Nos Références
#24
### Page Contact
- [ ] Le titre de la page à les bonnes marges et l'indication "[Contact]" est rajoutée
### Page Pharmacien
- [ ] Le titre de la page à les bonnes marges et l'indication "[Nos services]" est rajoutée
- [ ] Les marges correspondent aux maquettes pour la liste des statistiques
- [ ] Le slider est stylé
- [ ] Les besoins sont centrées dans les carrés

**Comment by hugobernard** [comment]
### Page Obtenir un devis
- [ ] La page est stylée / #28
