### ISSUE TITLE
La page de références est intégrée

### ISSUE THREAD

**Issue by piline** [Kozea/www-media#17]
Un wireframe a  été fait et présente, ce à quoi doit ressembler la page références : https://xd.adobe.com/view/92e8050f-cee9-4938-ac61-31d461e0943d

En attente d'Olivia pour les visuels cf Kozea/www-media#14  

Dans le HTML et CSS, un commentaire TODO est notifié

**Comment by hugobernard** [comment]
On peut voir ça ensemble si tu veux : https://github.com/Kozea/www-media/issues/24
