### ISSUE TITLE
Le slider de la page d'accueil est intégré

### ISSUE THREAD

**Issue by piline** [Kozea/www-media#18]
Un slider simple ou seuls les phrases bougent
https://drive.google.com/file/d/1auvwY-U2SioRunt0locwPgo8KAwl0xeJ/view?usp=sharing
https://drive.google.com/file/d/1mWBK3owPlFABxVksHbtQg54aJqEPpE9K/view?usp=sharing

Sur le CSS, il reste à ajouter le logo et fixer les éléments après intégration du slider

**Comment by liZe** [comment]
En attente de #11.
