### ISSUE TITLE
La page des mentions légales est terminée

### ISSUE THREAD

**Issue by annabellou** [Kozea/www-media#22]
Pour le moment on a simplement un lien dans le footer, mais il ne mène qu'à une page 404

**Comment by liZe** [comment]
La page a été ajoutée, en attente de #23 pour le contenu.

**Comment by oliviakozea** [comment]
https://docs.google.com/document/d/19oAhecx4jBNYT1hsMOAOqZBlDZ8sRj7VUxQMTzJ_lxc/edit?usp=sharing

**Comment by liZe** [comment]
Le contenu a été ajouté, reste le style.
