### ISSUE TITLE
La page Nos Références est Maquettée

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-media#24]
@Maxouuu Est-ce qu'on sait quel contenu il y aura sur cette page ?

**Comment by Maxouuu** [comment]
Olivia a un ticket là-dessus, elle va nous fournir le contenu

**Comment by hugobernard** [comment]
Cf la maquette dans la version V1 comme base.

**Comment by Maxouuu** [comment]
Contenu : 

Les références : 
Be Pharma / Groupement / sites internet + Facebook
Mutualpharmacie / Groupement / contenu (fiches santé)
Mutualpharm / Groupement / facebook
UPIE / Groupement / site + Facebook
Pharminfo / projet de refonte
Evolupharm / Laboratoire / la boutique
Pharmacie de checy / Pharmacie / Facebook

Les mots "additionnels" : Innovation / Esanté / Digital / Visibilité / Conseil / Accompagnement / Notoriété / Expertise /

**Comment by hugobernard** [comment]
![km-maquettes-web-www-v2-references](https://user-images.githubusercontent.com/20473458/39575623-836a17fa-4edb-11e8-8f12-c555afe685c9.jpg)
