### ISSUE TITLE
Le contenu des diaporamas des 3 pages clients est déterminé

### ISSUE THREAD

**Issue by liZe** [Kozea/www-media#26]
Sur les pages pharmacien, groupement et laboratoire, on a un diaporama avec photo et légende. Dans le contenu présenté dans #4, le contenu des diapositives a été esquissé, mais il faudrait plus de détails pour l'intégration.

Pour chaque diapositive, il nous faudrait :
- le texte de la légende, et
- une description du visuel souhaité.

Lorsque c'est prêt, merci de remettre #25 en urgent !

**Comment by Maxouuu** [comment]
@liZe Pour la V1, on met cette partie du site entre parenthèse. Pour la V2, nous intégrerons une vidéo d'Olivia à définir ultérieurement.
