### ISSUE TITLE
Les boutons du Pré-footer (aside) sont présent sur les pages Pharmacien, Laboratoire et Groupement

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-media#27]

**Comment by liZe** [comment]
Le deuxième bouton emmène sur quelle page ?

**Comment by Maxouuu** [comment]
Le premier bouton ramène toujours au devis
Le deuxième bouton ramène toujours à la page "Nos services"
Le 1ier bouton s'appelle "Obtenez un devis personnalisé"
Le 2e bouton s'appelle "Découvrez nos solutions"
