### ISSUE TITLE
Le formulaire pour obtenir un devis correspond au brief

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-media#28]
Il y a deux étapes :

https://docs.google.com/spreadsheets/d/1oB3tq5teTUAF6o94j9y3W7LLqVSw2E5-K3fDZOhQakk/edit?usp=sharing

**Comment by liZe** [comment]
@Maxouuu
- Il me faudrait les choix disponibles pour « Qui êtes-vous », « Quel est votre besoin » et « Quelle est votre cible ».
- J'avais simplifié les champs de la seconde étape pour qu'il y ait moins de boutons, mais je peux remettre les 5 s'il le faut.

**Comment by Maxouuu** [comment]
- Qui êtes-vous : Pharmacien / Responsable de groupement / Membre d'un laboratoire / Autre
- Quel est votre besoin : digitaliser votre activité / gagner en visibilité / augmenter votre CA / diffuser de l'information / Autre
- Quelle est votre cible : pharmaciens / patients / Autre 

Pour la seconde étape, tant qu'on a nom / téléphone / mail c'est bon

**Comment by liZe** [comment]
@Maxouuu @hugobernard Lorsque la demande a été faite, il y a un message de confirmation dans le HTML mais il ne s'affiche pas pour l'instant. Il faudrait faire du style pour qu'il s'affiche, je vous laisse voir ensemble si vous faites un ticket pour ça.
