### ISSUE TITLE
Le contenu du site www-media est écrit 

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-media#4]
Se référer aux encadrés bleus sur la maquette pour la Correction/rédaction du contenu
https://drive.google.com/open?id=0BwBm6Evb-akbb2lXanZpV3FFUk0

**Comment by Maxouuu** [comment]
https://docs.google.com/a/kozea.fr/spreadsheets/d/1oB3tq5teTUAF6o94j9y3W7LLqVSw2E5-K3fDZOhQakk/edit?usp=sharing
