### ISSUE TITLE
Les liens des réseaux sociaux et l'inscription à la newsletter sont implémentés

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-media#52]

**Comment by liZe** [comment]
Pour les réseaux sociaux, des liens dans la partie « contact » du footer.
Pour l'inscription à la newsletter, un `aside` avec le formulaire.

**Comment by liZe** [comment]
@oliviakozea Merci de me filer le lien pour l'inscription à la newsletter !

**Comment by oliviakozea** [comment]
et voici ! 
http://eepurl.com/cY2PQf

merci

**Comment by liZe** [comment]
@hugobernard On n'a pas trop la main sur le formulaire de Mailchimp, je l'ai simplifié au maximum et je pense que ça devrait t'aller. J'ai aussi corrigé le Sass/CSS pour l'id que j'ai mis sur le tag aside.
