### ISSUE TITLE
Le blog est implémenté

### ISSUE THREAD

**Issue by hugobernard** [Kozea/www-media#58]
### Sur la page d'accueil :
Emplacement : juste avant le bloc Obtenir un devis
Apparance : Comme sur pharminfo.fr
### La page Nos actualités
Du coup il faut aussi une page avec tous les articles et un onglet dans le menu

**Comment by liZe** [comment]
Comme indiqué dans a460a49, il restera juste à changer l'id de la catégorie dans la fonction `get_news()`.
