### ISSUE TITLE
Les fautes sont corrigées sur le site 

### ISSUE THREAD

**Issue by Maxouuu** [Kozea/www-media#63]
- [ ] Sur l'ensemble du site il faut écrire "Kozea media" (pas de majuscule à Media)

- [ ] Sur l'ensemble du site il faut écrire "Kozea group" (pas de majuscule à Group)

- [ ] JE SUIS PHARMACIEN : 1ière phrase : Connectons (et non Connections)

- [ ] JE SUIS PHARMACIEN : remplacer la 1ère phrase "Connections l'officine et la patientèle" par la phrase "Connectons la pharmacie à sa patientèle"

- [ ] JE SUIS UN GROUPEMENT : dans la rubrique Besoins écrire "sur-mesure" avec un tiret 

- [ ] A PROPOS / L'AGENCE : remplacer "elle est créée ... et animée" par "elle a été créée ... et est animée"

- [ ] A PROPOS / L'AGENCE : écrire "sur-mesure" avec un tiret 

- [ ] NOS SERVICES / VOUS ÊTES : remplacer "nous nous adoptons" par "nous nous adaptons"

- [ ] A PROPOS / AUJOURD'HUI : le texte sous aujourd'hui est changé en "Kozea media s'appuie sur des données fortes pour réaliser tous vos projets"

- [ ] NOS GARANTIES : toutes les conjugaison sont à l'impératif (EZ à la fin des verbes) : boostez, osez, améliorez, confiez, accompagnez,...)

**Comment by liZe** [comment]
J'ai mis « sur-mesure » avec un trait d'union, mais il me semble qu'on ne le met que si l'expression est utilisée comme nom (le sur-mesure) et pas comme complément du nom (le service sur mesure).
