### ISSUE TITLE
L'ajout d'une pop-up lors de l'arrivée sur le site est analysé

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-media#78]
Pour indiquer l'offre spéciale avec un bouton d'action contact 
(brief à venir)

**Comment by Lilouu** [comment]
Face à l'actualité nous tenons à vous assurer que l'ensemble des équipes de Kozea media est mobilisée pour assurer la continuité de nos missions à votre service. Et pour vous soutenir dans cette épreuve, nous souhaitons vous accompagner davantage en vous proposant **une page Facebook alimentée régulièrement à 1€ / mois pendant 2 mois, sans engagement.**

Bouton d'action : **Contactez-nous pour en savoir plus**
Qui redirige vers le mail media@kozea.fr

**Comment by annabellou** [comment]
Voici ma proposition : 

![Bandeau Kozea media](https://user-images.githubusercontent.com/7512422/77157416-975db080-6aa1-11ea-8982-c71630f1ab2f.png)

Après avoir fait le tour de plusieurs sites de vente en ligne, il en est ressorti que la tendance était plutôt au bandeau de texte qu’à une pop up.
Je propose donc un simple bandeau de texte, placé en bas de page, qui reste fixe même en scrollant la page. Il n’y a pas de possiblité de fermer / cacher ce bandeau. L’offre est mise en valeur ainsi que le bouton de contact.

Qu’en penses-tu @Lilouu ?

**Comment by Lilouu** [comment]
Comme Pharminfo.fr très bien ça me va !
