### ISSUE TITLE
Le bandeau de texte est mis en prod

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-media#79]
Suite #78

**Comment by gentooboontoo** [comment]
@annabellou, @Lilouu  est-ce que ça vous convient ?

https://test-www-media-specialoffer.kozea.fr/

**Comment by Lilouu** [comment]
Yes !

**Comment by annabellou** [comment]
Ça me convient aussi !

**Comment by gentooboontoo** [comment]
Merci. Déployé.
