### ISSUE TITLE
La mise à jour de l'équipe est faite

### ISSUE THREAD

**Issue by gentooboontoo** [Kozea/www-media#82]
@Lilouu, j'ai rétabli l'ancienne version pour le moment. À partir des critères que tu as définis, je te laisse m'indiquer les changements à apporter sur cette section (personnes à inclure ou non et fonction).

**Comment by Lilouu** [comment]
Je pense qu'il faut garder les personnes qui travaillent vraiment sur le projet de Kozea media, pour faciliter la prise de contact avec les bonnes personnes si besoin pour les prospects. 
Je serais donc plutôt d'avis de laisser comme ça, en remplaçant Guillaume par toi du coup en tant que responsable technique.
