### ISSUE TITLE
Le site internet est adapté à la nouvelle charte graphique

### ISSUE THREAD

**Issue by Lilouu** [Kozea/www-media#86]
Concernant la mise à jour du site internet Kozea group avec la nouvelle charte graphique, ça impacte donc Kozea media : nouveau logo, nouvelle couleur, nouvelle police. 
Pour la sortie du site internet Kozea group et de notre nouvelle identité (13/09), l'idée serait donc d'adapter la charte graphique du site de Kozea media en même temps pour rester cohérent.

**Comment by annabellou** [comment]
Je m'assigne ce ticket à la place de @gentooboontoo.

**Comment by annabellou** [comment]
Mise en production ce jour, je ferme le ticket.
